// client/src/types/questionBankTypes.ts

// Corresponds to QuestionModel.ts on the backend
export interface IOption {
  _id?: string; // Optional because it's generated by DB for new options
  text: string;
  isCorrect: boolean;
}

export type QuestionType =
  | "multiple-choice-single"
  | "multiple-choice-multiple"
  | "true-false";

// Knowledge category types (matching backend)
export enum KnowledgeCategory {
  FOOD_KNOWLEDGE = "food-knowledge",
  BEVERAGE_KNOWLEDGE = "beverage-knowledge",
  WINE_KNOWLEDGE = "wine-knowledge",
  PROCEDURES_KNOWLEDGE = "procedures-knowledge",
}

export interface IQuestion {
  _id: string;
  questionText: string;
  questionType: QuestionType;
  options: IOption[];
  categories: string[]; // From MenuItem categories or custom
  restaurantId: string;
  createdBy: "ai" | "manual";
  explanation?: string;
  createdAt: string;
  updatedAt: string;
  status: "active" | "pending_review" | "rejected";

  // Knowledge Analytics fields
  knowledgeCategory: KnowledgeCategory;
  knowledgeSubcategories?: string[];
  knowledgeCategoryAssignedBy: "manual" | "ai" | "restaurant_edit";
  knowledgeCategoryAssignedAt: string;
  knowledgeCategoryLastEditedBy?: string;
}

// Main interface for a Question Bank document on the client-side
export interface IQuestionBank {
  _id: string;
  name: string;
  description?: string;
  restaurantId: string; // Assuming this is always populated or available
  sourceType: "SOP" | "MENU" | "MANUAL"; // Added sourceType
  sourceSopDocumentId?: string | null; // Added for SOP source
  sourceSopDocumentTitle?: string; // Added for SOP source, if backend provides it
  sourceMenuId?: string | null; // Added for Menu source
  sourceMenuName?: string; // Added for Menu source, if backend provides it
  categories: string[];
  questions: string[] | IQuestion[]; // Array of question IDs or populated question objects
  questionCount: number;
  createdAt: string; // Date as string
  updatedAt: string; // Date as string
  // createdBy?: string; // Optional: if you need to display who created it
}

// For creating a new question bank
export interface CreateQuestionBankData {
  name: string;
  description?: string;
}

// For updating a question bank
export interface UpdateQuestionBankData {
  name?: string;
  description?: string;
  categories?: string[]; // ADDED: To allow updating categories
  // questionIds?: string[]; // For managing questions within a bank later
}

// For AI Question Generation (mirrors backend AiGenerationParams, ommitting restaurantId)
export interface AiGenerationClientParams {
  categories: string[];
  targetQuestionCount: number;
  menuContext?: string;
  geminiModelName?: string;
  bankId?: string; // ADDED: To associate generated questions with a bank
}

// Specific AI params for creating bank from menu (subset of AiGenerationClientParams)
export interface MenuAiGenerationClientParams {
  targetQuestionCount?: number;
  // geminiModelName?: string;
  // selectedFocusAreas?: string[];
  // difficultyLevel?: string;
  // questionTypes?: string[];
}

// This will be the main type for creating any question bank from the client
export interface CreateQuestionBankClientData {
  name: string;
  description?: string;
  restaurantId: string; // Assuming client always knows this now

  sourceType: "MANUAL" | "MENU" | "SOP"; // Changed to uppercase

  // For Menu source
  sourceMenuId?: string;
  categoriesToInclude?: string[]; // ADDED: For non-beverage/main categories from menu
  beverageCategoriesToInclude?: string[]; // ADDED: For selected beverage categories from menu

  // For SOP source
  sourceSopDocumentId?: string;
  // For SOP, 'categories' (if used) would mean selected SOP section names for the bank
  // If creating bank from SOP and auto-populating categories, it might still use 'categoriesToInclude'
  // or a specific field like 'sopCategoryNames'. For clarity, if SOP uses this DTO directly
  // and needs to specify which SOP sections become bank categories, a distinct field or convention is needed.
  // For now, assuming SOP creation might still use categoriesToInclude if applicable for its sections.
  categories?: string[]; // RETAINED: For SOP category selection, but needs clarification if MENU uses categoriesToInclude

  generationMethod?: "AI" | "MANUAL"; // MODIFIED to uppercase

  // Note: AI generation parameters for menu (like targetQuestionCount)
  // are not directly part of this top-level type anymore.
  // If createQuestionBankFromMenu service on backend handles AI params,
  // they would be passed there, not to the generic /question-banks endpoint directly.
}

// For creating an individual question manually (client-side)
export interface NewQuestionClientData {
  questionText: string;
  questionType: QuestionType;
  options: Omit<IOption, "_id">[];
  categories: string[];
  questionBankId: string;

  // Knowledge Analytics fields
  knowledgeCategory: KnowledgeCategory;
  knowledgeSubcategories?: string[];
}

// For updating an individual question (client-side)
// Note: questionType is generally not updated directly; delete and re-create if type change is needed.
export interface UpdateQuestionClientData {
  questionText?: string;
  questionType?: QuestionType;
  options?: Omit<IOption, "_id">[]; // Options might be entirely new or have existing _ids for merging on backend (if supported)
  categories?: string[];
  explanation?: string; // Ensure explanation is present

  // Knowledge Analytics fields
  knowledgeCategory?: KnowledgeCategory;
  knowledgeSubcategories?: string[];
}

// Payload for the new AI Question Generation Process via /api/ai/generate-questions
export interface NewAiQuestionGenerationParams {
  bankId: string; // ADDED: To link generated questions to the correct bank
  menuId: string;
  categoriesToFocus: string[];
  questionFocusAreas: string[];
  targetQuestionCountPerItemFocus: number;
  questionTypes: string[];
  additionalContext?: string;
  itemIds?: string[];
}
